test_secretary/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

import unittester.urls

urlpatterns = patterns('',
    url(r'^$', 'test_secretary.views.home', name='overview'),
    url(r'^testrun/(?P<rid>\d+)/?$', 'test_secretary.views.testrun_overview',
        name='testrun_overview'),
    url(r'^testrun/new/?$', 'test_secretary.views.new_testrun',
        name='new_testrun'),
    url(r'^testrun/append/(?P<trid>\d+)/?$',
        'test_secretary.views.append_testcases',
        name='append_testcases'),
    url(r'^testcaserun/edit/(?P<trid>\d+)/(?P<elemno>\d+)/?$',
        'test_secretary.views.edit_testcaserun',
        name='edit_testcaserun_multiple'),
    url(r'^testcaserun/edit/(?P<tcrid>\d+)/?$',
        'test_secretary.views.edit_testcaserun_single',
        name='edit_testcaserun_single'),
    url(r'^testcaserun/setstatus/(?P<tcrid>\d+)/(?P<status>[A-Z]{2,3})/?$',
        'test_secretary.views.set_testcaserun_status',
        name='set_testcaserun_status'),
    url(r'^app/(?P<aid>\d+)/(?P<all>all)?/?$',
        'test_secretary.views.app_overview',
        name='app_overview'),

    url(r'^unittester/', include(unittester.urls, namespace='unittester',
        app_name='unittester')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        name='generic_login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
        name='generic_logout'),
)

unittester/urls.py
from django.conf.urls import patterns, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^testcaserun/run/(?P<tcrid>\d+)/?$',
        'unittester.views.run_testcaserun', name='testcaserun'),
)

test_secretary/models.py
from dateutil import tz
from datetime import datetime

from django.db import models
from django.core import urlresolvers
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django_extensions.db.fields import ModificationDateTimeField
from django.utils.translation import ugettext as _


STATUS = (('NT', 'untested'),
          ('OK', 'success'),
          ('NOK', 'failed'),
          ('DN', 'decision needed'))


class AdminUrlMixIn():
    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        name = 'admin:%s_%s_change' % (content_type.app_label,
                                       content_type.model)
        return urlresolvers.reverse(name, args=(self.pk,))


class Application(models.Model, AdminUrlMixIn):
    name = models.CharField(max_length=50)
    order = models.PositiveIntegerField(blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('order', 'name')

    @property
    def active_sections(self):
        return self.testsection_set.filter(active=True)


class TestSection(models.Model, AdminUrlMixIn):
    name = models.CharField(max_length=50)
    app = models.ForeignKey(Application)
    active = models.BooleanField(default=True)
    order = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return '%s - %s' % (self.app, self.name)

    @property
    def active_testcases(self):
        return self.testcase_set.filter(active=True)

    class Meta:
        unique_together = ('name', 'app')
        ordering = ('app', 'order', 'name')


class TestCase(models.Model, AdminUrlMixIn):
    order = models.PositiveIntegerField(null=True, blank=True)
    name = models.CharField(max_length=100)
    section = models.ForeignKey(TestSection)
    active = models.BooleanField(default=True)
    autotest_exists = models.BooleanField(default=False)
    description = models.TextField(null=True, blank=True)
    preconditions = models.ManyToManyField('self', through='Precondition',
                                           null=True, blank=True,
                                           symmetrical=False,
                                           related_name='precondition_set')
    action = models.TextField(null=True, blank=True)
    expected = models.TextField(null=True, blank=True)

    def __str__(self):
        return '%s - %s' % (self.section, self.name)

    class Meta:
        get_latest_by = 'pk'
        ordering = ('section', 'order', 'name')


class Precondition(models.Model, AdminUrlMixIn):
    testcase = models.ForeignKey(TestCase, related_name='from_testcase')
    precondition = models.ForeignKey(TestCase, related_name='precondition')
    comment = models.TextField(null=True, blank=True)


class TestRun(models.Model, AdminUrlMixIn):
    name = models.CharField(max_length=50)
    comment = models.TextField(null=True, blank=True)
    version = models.CharField(max_length=40)
    date = models.DateTimeField(default=datetime.now, blank=True)
    testcases = models.ManyToManyField(TestCase, through='TestCaseRun')
    user = models.ForeignKey(User)

    def has_testcase_assigned(self, testcase):
        return TestCaseRun.objects.filter(
            testrun=self, testcase=testcase
        ).exists()

    def __str__(self):
        t = self.date.astimezone(tz.tzlocal())
        timestring = t.strftime('%Y-%m-%d %H:%M')
        return '[%s] %s' % (timestring, self.name)

    @property
    def assigned_applications(self):
        testcase_ids = self.testcaserun_set.values('testcase_id')
        return Application.objects.filter(
            testsection__testcase__id__in=testcase_ids).distinct()

    class Meta:
        get_latest_by = 'date'
        ordering = ['-date']
        permissions = (
            ("view_testruns", _("Can see own tests running")),
            ("view_other_testruns", _("Can see all tests running")),
        )

    @property
    def is_finished(self):
        """ no untested or undecided testcases
        """
        return self.todo_count + self.decision_count == 0

    @property
    def is_success(self):
        """ nothing failed, also check is_finished
            unfinished testruns can also be successfully if nothing failed yet
        """
        return self.failed_count == 0

    @property
    def success_count(self):
        return self.testcaserun_set.filter(status='OK').count()

    @property
    def failed_count(self):
        return self.testcaserun_set.filter(status='NOK').count()

    @property
    def todo_count(self):
        return self.testcaserun_set.filter(status='NT').count()

    @property
    def decision_count(self):
        return self.testcaserun_set.filter(status='DN').count()


class TestCaseRun(models.Model, AdminUrlMixIn):
    testcase = models.ForeignKey(TestCase)
    testrun = models.ForeignKey(TestRun)
    status = models.CharField(max_length=3, choices=STATUS, default='NT')
    comment = models.TextField(null=True, blank=True)
    modified = ModificationDateTimeField(help_text=_('Last Status Change'))
    editor = models.ForeignKey(User, help_text=_('Last Editor'))

    def __str__(self):
        return '%s: %s' % (self.testrun, self.testcase)

    class Meta:
        ordering = ('testcase__section__app__name', 'testcase__section__order',
                    'testcase__section__name', 'testcase__order')
        permissions = (
            ("view_testcaserun_status", _("Can see own tests running")),
        )

unittester/models.py
from django.db import models

from test_secretary.models import TestCase, TestCaseRun


class UnitTest(models.Model):
    test_module = models.CharField(max_length=255, unique=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    testcases = models.ManyToManyField(TestCase, null=True, blank=True)

    def __str__(self):
        if self.name:
            return '%s [%s]' % (self.name, self.test_module)
        else:
            return '%s' % self.test_module


class UnitTestRun(models.Model):
    unittest = models.ForeignKey(UnitTest)
    testcaserun = models.ForeignKey(TestCaseRun)
    date = models.DateTimeField(auto_now=True)
    errors = models.PositiveIntegerField(default=0)
    failures = models.PositiveIntegerField(default=0)
    tests_run = models.PositiveIntegerField(default=0)
    description = models.TextField(blank=True, null=True)

    def is_success(self):
        return self.errors+self.failures == 0

    def __str__(self):
        return "[%s] %s" % (self.date.strftime('%Y-%m-%d %X'),
                            self.unittest.name)

test_secretary/forms.py
from django import forms

from test_secretary.models import TestCaseRun, STATUS


class TestCaseRunForm(forms.ModelForm):
    class Meta:
        model = TestCaseRun
        fields = ['status', 'comment']
        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control form-element',
                                             'placeholder': 'Optional comment'}),
            'status': forms.Select(attrs={'class': 'form-control form-element'},
                                   choices=STATUS),
        }

test_secretary/views.py
import re
import logging
import itertools
from datetime import datetime

from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, permission_required

from .models import *
from .forms import TestCaseRunForm
from . import compat


TCREGEX = re.compile('testcase(?P<tcid>\d+)')

logger = logging.Logger('test_secretary#views')


def home(request):
    d = {}
    d['apps'] = Application.objects.all()

    testruns = {}
    if request.user.has_perm('test_secretary.view_testruns'):
        if request.user.has_perm('test_secretary.view_other_testruns'):
            testruns['other'] = TestRun.objects.exclude(user=request.user)
        testruns['own'] = TestRun.objects.filter(user=request.user)

    d['testruns'] = testruns
    return render(request, 'test_secretary/overview.html', d)


def app_overview(request, aid, all=False):
    d = {'active': not all}
    d['app'] = Application.objects.get(pk=aid)
    return render(request, 'test_secretary/app_overview.html', d)


@login_required
@permission_required('test_secretary.view_testruns', raise_exception=True)
def testrun_overview(request, rid):
    c = itertools.count()
    if not hasattr(c, '__next__'):
        c = compat.count()

    d = {'counter': c}

    testrun = get_object_or_404(TestRun, pk=rid)

    d['testrun'] = testrun
    d['testcaseruns'] = testrun.testcaserun_set.all()

    return render(request, 'test_secretary/testrun_overview.html', d)


@login_required
@permission_required('test_secretary.add_testrun', raise_exception=True)
def new_testrun(request):
    d = {}
    if request.method == 'POST':
        tstr = datetime.now().strftime('%c')
        name = request.POST.get('name', 'TestRun %s' % tstr)
        comment = request.POST.get('comment', None)
        version = request.POST.get('version', 'undefined')
        testcase_ids = [TCREGEX.match(elem).groupdict()['tcid']
                        for elem in request.POST if TCREGEX.match(elem)]
        # get TestCases from ids
        # XXX using ids should be sufficient
        testcases = [TestCase.objects.get(pk=tcid) for tcid in testcase_ids]

        if testcases:
            logger.info('Saving new TestRun: %s' % name)
            testrun = TestRun(name=name, comment=comment, version=version,
                              user=request.user)
            testrun.save()
            for testcase in testcases:
                tcr = TestCaseRun(testcase=testcase, testrun=testrun,
                                  editor=request.user)
                tcr.save()
            return HttpResponseRedirect(reverse('testrun_overview',
                                        kwargs={'rid': testrun.pk}))
        else:
            d['errmsg'] = 'No testcases selected'

    d['apps'] = Application.objects.filter(active=True)
    return render(request, 'test_secretary/new_testrun.html', d)


@login_required
def append_testcases(request, trid):
    d = {}
    testrun = get_object_or_404(TestRun, pk=trid)
    d['testrun'] = testrun

    if request.method == 'POST':
        testcase_ids = [TCREGEX.match(elem).groupdict()['tcid']
                        for elem in request.POST if TCREGEX.match(elem)]

        if testcase_ids:
            logger.info('Append %d TestCases to %s' % (len(testcase_ids),
                                                       testrun))
            for testcase_id in testcase_ids:
                TestCaseRun.objects.create(testrun=testrun,
                                           testcase_id=testcase_id,
                                           editor=request.user)
            return HttpResponseRedirect(reverse('testrun_overview',
                                        kwargs={'rid': testrun.pk}))
        else:
            d['errmsg'] = 'No testcases selected'

    d['apps'] = Application.objects.filter(active=True)
    return render(request, 'test_secretary/append_testcases.html', d)


@login_required
@permission_required('test_secretary.change_testcaserun', raise_exception=True)
def edit_testcaserun_single(request, tcrid):
    d = {'saved': False}

    testcaserun = get_object_or_404(TestCaseRun, pk=tcrid)
    d['testcaserun'] = testcaserun

    if request.method == 'POST':
        testcaserun_form = TestCaseRunForm(request.POST, instance=testcaserun)
        if testcaserun_form.is_valid():
            testcaserun_form.save()
            testcaserun = TestCaseRun.objects.get(pk=testcaserun.pk)
            testcaserun.editor = request.user
            testcaserun.save()
            d['saved'] = True
    else:
        testcaserun_form = TestCaseRunForm(instance=testcaserun)

    d['testcaserun_form'] = testcaserun_form
    return render(request, 'test_secretary/edit_testcaserun_single.html', d)


@login_required
@permission_required('test_secretary.change_testcaserun', raise_exception=True)
def edit_testcaserun(request, trid, elemno):
    d = {'saved': False}
    elemno = int(elemno)
    d['elemno'] = elemno

    testrun = get_object_or_404(TestRun, pk=trid)
    testcaseruns = TestCaseRun.objects.filter(testrun=testrun)

    tcr_count = testcaseruns.count()
    if elemno < tcr_count:
        testcaserun = testcaseruns[elemno]
    else:
        testcaserun = testcaseruns[tcr_count-1]
        d['elemno'] = tcr_count-1

    d['is_last'] = elemno >= tcr_count-1

    if request.method == 'POST':
        testcaserun_form = TestCaseRunForm(request.POST, instance=testcaserun)
        if testcaserun_form.is_valid():
            testcaserun_form.save()
            testcaserun = TestCaseRun.objects.get(pk=testcaserun.pk)
            testcaserun.editor = request.user
            testcaserun.save()
            d['saved'] = True
    else:
        testcaserun_form = TestCaseRunForm(instance=testcaserun)

    d['testcaserun'] = testcaserun
    d['testcaserun_form'] = testcaserun_form
    return render(request, 'test_secretary/edit_testcaserun_multiple.html', d)


@login_required
@permission_required('test_secretary.change_testcaserun', raise_exception=True)
def set_testcaserun_status(request, tcrid, status):
    testcaserun = get_object_or_404(TestCaseRun, pk=tcrid)
    if status in list(zip(*STATUS))[0]:
        testcaserun.status = status
        testcaserun.editor = request.user
        testcaserun.save()
    return HttpResponse('')

test_secretary/templates/test_secretary/app_overview.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}{{ app }} - Test Secretary{% endblock %}

{% block scripts %}
  <script src="{% static 'js/jquery.sortable.js' %}"></script>
  <script src="{% static 'js/sort_testcases.js' %}"></script>
  <script>
    function sort_enable() {
      $('.sortable').sortable('enable');
      $('.edit').fadeIn();
    }
    function sort_disable() {
      $('.sortable').sortable('disable');
      $('.edit').fadeOut();
    }
    function sort_toggle(elem) {
      if(elem.checked) {
        sort_enable();
      } else {
        sort_disable();
      }
    }
    // sorting disable by default
    $('.sortable').sortable('disable');
    $('.edit').hide();
  </script>
{% endblock %}

{% block main %}
  <div class="header">
    <h1 class="inline">{{ app }}</h1>
    <a href="{{ app.get_admin_url }}" target="_blank">
      <button class="btn btn-primary btn-xs" style="vertical-align:top;">Edit</button>
    </a>
    <span class="inline" style="font-size:15px;vertical-align:middle;">
      Show:
      {% if active %}
        <a href="{% url 'app_overview' app.pk 'all' %}">
      {% else %}
        <a href="{% url 'app_overview' app.pk %}">
      {% endif %}
        <input type="checkbox" class="switch" data-on-text="all" data-off-text="active"
        {% if not active %}CHECKED{% endif %}>
      </a>
    </span>
    <span class="inline">
      Sorting:
      <input type="checkbox" class="switch" data-on-text="on" data-off-text="off"
      onchange="sort_toggle(this);">
    </span>
  </div>

  {% for section in app.active_sections %}
    <h3>{{ section.name }}</h3>
    {% if section.active_testcases.count %}
      <table class="table table-bordered table-striped">
        <thead>
          <th class="edit"></th>
          <th>#</th>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Description" %}</th>
          <th>{% trans "Action" %}</th>
          <th>{% trans "Expected" %}</th>
        </thead>
        <tbody class="sortable">
          {% if active %}
            {% for testcase in section.active_testcases %}
              <tr>
                <td class="edit"><span class="handle">:: </span></td>
                <td>{{ testcase.order }}</td>
                <td>
                  {{ testcase.name }}
                  {% if testcase.autotest_exists %}
                    <span class="label label-primary">Automatic test</span>
                  {% endif %}
                </td>
                <td>{{ testcase.description|default:"-"|linebreaksbr }}</td>
                <td>{{ testcase.action|default:"-"|linebreaksbr }}</td>
                <td>{{ testcase.expected|default:"-"|linebreaksbr }}</td>
              </tr>
            {% endfor %}
          {% else %}
            {% for testcase in section.testcase_set.all %}
              <tr class="{% if not testcase.active %} text-muted{% endif %}">
                <td class="edit"><span class="handle">:: </span></td>
                <td>{{ testcase.order }}</td>
                <td>{{ testcase.name }}</td>
                <td>{{ testcase.description|default:"-"|linebreaksbr }}</td>
                <td>{{ testcase.action|default:"-"|linebreaksbr }}</td>
                <td>{{ testcase.expected|default:"-"|linebreaksbr }}</td>
              </tr>
            {% endfor %}
          {% endif %}
        </tbody>
      </table>
    {% else %}
      <div class="alert alert-info">
        No testcases in this sections
      </div>
    {% endif %}
  {% empty %}
    <div class="alert alert-info">
      No sections in this app
    </div>
  {% endfor %}

  <a href="{% url 'overview' %}" class="btn btn-info">Overview</a>
{% endblock %}

test_secretary/templates/test_secretary/append_testcases.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}Append TestCases - Test Secretary{% endblock %}

{% block main %}
  <h1>Append TestCases</h1>

  {% if errmsg %}
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong>Error!</strong> {{ errmsg }}
    </div>
  {% endif %}
  {% if warnmsg %}
    <div class="alert alert-dismissable alert-warning">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong>Warning!</strong> {{ errmsg }}
    </div>
  {% endif %}

  <form method='POST' action='{% url "append_testcases" testrun.pk %}' class='form-element'>
    {% csrf_token %}

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          {% trans "TestRun Information" %}
        </h3>
      </div>
      <div class="panel-body">
        <p>
          <span><strong>Name: </strong>{{ testrun.name }}</span>
        </p>
        <p>
          <span><strong>Comment: </strong>{{ testrun.comment }}</span>
        </p>
        <p>
          <span><strong>Version: </strong>{{ testrun.version }}</span>
        </p>
      </div>
    </div>

    {% include 'test_secretary/testcase_panels.html' %}

    <input type='submit' class="btn btn-primary" value='{% trans "Save TestRun" %}'/>
  </form>

  <a href="{% url 'overview' %}" class="btn btn-info">Overview</a>

{% endblock %}

test_secretary/templates/test_secretary/edit_testcaserun.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block main %}
  {% if saved %}
    <div class="alert alert-success alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      {% trans "TestCaseRun saved" %}
    </div>
  {% endif %}

  {% if testcaserun_form.errors %}
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      {{ testcaserun_form.errors }}
    </div>
  {% endif %}

  <h1>{{ testcaserun.testrun }}</h1>
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong>{{ testcaserun.testcase }}</strong>
      <a href="{{ testcaserun.testcase.get_admin_url }}" target="_blank">
        <button class="btn btn-primary btn-xs" style="vertical-align:top;">Edit</button>
      </a>
    </div>

    <div class="panel-body">
      <dl class="dl-horizontal">
        <dt>{% trans 'Description' %}</dt>
        <dd>{{ testcaserun.testcase.description|default:'-'|linebreaksbr }}</dd>
        <dt>{% trans 'Action' %}</dt>
        <dd>{{ testcaserun.testcase.action|default:'-'|linebreaksbr }}</dd>
        <dt>{% trans 'Expected' %}</dt>
        <dd>{{ testcaserun.testcase.expected|default:'-'|linebreaksbr }}</dd>
      </dl>
    </div>
  </div>

  <form role="form" method=POST action="">
    {% csrf_token %}
    {{ testcaserun_form }}
    <input type="submit" value="Save" class="btn btn-success form-element"></input>
    {% block form_buttons_bottom %}{% endblock %}
  </form>

  {% block bottom %}
    <a href="{% url 'testrun_overview' testcaserun.testrun.pk %}" class="btn btn-info">TestRun</a>
    {% if testcaserun.testcase.unittest_set.count %}
      <a href="{% url 'unittester:testcaserun' testcaserun.pk %}" class="btn btn-primary">Automatic tests</a>
    {% else %}
      <a href="#" class="btn btn-primary" disabled="disabled">Automatic tests</a>
    {% endif %}
  {% endblock %}
{% endblock %}

test_secretary/templates/test_secretary/edit_testcaserun_single.html
{% extends "test_secretary/edit_testcaserun.html" %}

{% load i18n %}
{% load static %}

<a href="{% url 'testrun_overview' testcaserun.testrun.pk %}" class="btn btn-info">TestRun</a>

test_secretary/templates/test_secretary/testcaserun_table.html
{% load i18n %}
{% load iterator %}

{% include 'test_secretary/testcaserun_table.js' %}

{# XXX generates huge amount of queries #}
{% regroup testcaseruns by testcase.section.app as testcaseruns_group_app %}

{% for testcaserun_app in testcaseruns_group_app %}
  <div class="break-after avoid-break-inside">
    <h2>
      {{ testcaserun_app.grouper.order|default:'#' }}.
      {{ testcaserun_app.grouper.name }}
    </h2>
    {% regroup testcaserun_app.list by testcase.section as testcaseruns_group_section %}
    {% for testcaserun_section in testcaseruns_group_section %}
      <h3>
        {{ testcaserun_app.grouper.order|default:'#' }}.{{ testcaserun_section.grouper.order|default:'#' }}
        {{ testcaserun_section.grouper.name }}
      </h3>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>{% trans "Testcase" %}</th>
            <th>{% trans "Description" %}</th>
            <th>{% trans "Preconditions" %}</th>
            <th>{% trans "Action" %}</th>
            <th>{% trans "Expected" %}</th>
            {% if perms.test_secretary.view_testcaserun_status or testcase.user == user %}
              <th>{% trans "Status" %}</th>
            {% endif %}
          </tr>
        </thead>
        <!--<tfoot>
          <tr>
            <td>no footer yet</td>
            <td>tbd</td>
          </tr>
        </tfoot>-->
        <tbody>
          {% for testcaserun in testcaserun_section.list %}
            <tr{% if not testcaserun.testcase.active %} class="text-muted"{% endif %}>
              <td style="width: 3em;">{{ testcaserun.testcase.order|default:'#' }}</td>
              <td style="width: 15%">{{ testcaserun.testcase.name }}</td>
              <td>{{ testcaserun.testcase.description|default:""|linebreaksbr }}</td>
              <td style="width: 15%">
                {% if testcaserun.testcase.preconditions.exists %}
                  <ul>
                    {% for precondition in testcaserun.testcase.preconditions.all %}
                      <li><a href"#{{ precondition.pk }}">{{ precondition.name }}</a></li>
                    {% endfor %}
                  </ul>
                {% endif %}
              </td>
              <td style="width: 15%">{{ testcaserun.testcase.action|default:""|linebreaksbr }}</td>
              <td style="width: 15%">{{ testcaserun.testcase.expected|default:""|linebreaksbr }}</td>
              {% if perms.test_secretary.view_testcaserun_status or testcase.user == user %}
                <td id="status{{ testcaserun.pk }}" style="width: 6em;" title="{{ testcaserun.comment|default:'' }}">
                  {% if testcaserun.testcase.autotest_exists %}<span class="label label-primary">Automatic test</span><br>{% endif %}
                  {% if testcaserun.status == 'OK' %}
                    <a href="{% url 'edit_testcaserun_multiple' testrun.pk counter|next %}">
                      <span class="label label-success state-label">
                        {{ testcaserun.get_status_display }}
                      </span>
                    </a>
                    {# XXX #}
                    <button type="button" href="{% url 'set_testcaserun_status' testcaserun.pk 'NT' %}" class="btn btn-default btn-xs shown" onclick="set_testcaserun_status({{ testcaserun.pk }}, 'NT')" style="margin-top: 0.5em;">
                      Set untested
                    </button>
                    <button type="button" href="{% url 'set_testcaserun_status' testcaserun.pk 'OK' %}" class="btn btn-default btn-xs hidden" onclick="set_testcaserun_status({{ testcaserun.pk }}, 'OK')" style="margin-top: 0.5em;">
                      Set success
                    </button>
                  {% elif testcaserun.status == 'NOK' %}
                    <a href="{% url 'edit_testcaserun_multiple' testrun.pk counter|next %}">
                      <span class="label label-danger state-label">
                        {{ testcaserun.get_status_display }}
                      </span>
                    </a>
                  {% elif testcaserun.status == 'NT' %}
                    <a href="{% url 'edit_testcaserun_multiple' testrun.pk counter|next %}">
                      <span class="label label-default state-label">
                        {{ testcaserun.get_status_display }}
                      </span>
                    </a>
                    {# XXX #}
                    <button type="button" href="{% url 'set_testcaserun_status' testcaserun.pk 'OK' %}" class="btn btn-default btn-xs shown" onclick="set_testcaserun_status({{ testcaserun.pk }}, 'OK')" style="margin-top: 0.5em;">
                      Set success
                    </button>
                    <button type="button" href="{% url 'set_testcaserun_status' testcaserun.pk 'NT' %}" class="btn btn-default btn-xs hidden" onclick="set_testcaserun_status({{ testcaserun.pk }}, 'NT')" style="margin-top: 0.5em;">
                      Set untested
                    </button>
                  {% elif testcaserun.status == 'DN' %}
                    <a href="{% url 'edit_testcaserun_multiple' testrun.pk counter|next %}">
                      <span class="label label-info state-label">
                        {{ testcaserun.get_status_display }}
                      </span>
                    </a>
                  {% endif %}
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% endfor %}
{% endfor %}