test_secretary/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

import unittester.urls

urlpatterns = patterns('',
    url(r'^$', 'test_secretary.views.home', name='overview'),
    url(r'^testrun/(?P<rid>\d+)/?$', 'test_secretary.views.testrun_overview',
        name='testrun_overview'),
    url(r'^testrun/new/?$', 'test_secretary.views.new_testrun',
        name='new_testrun'),
    url(r'^testrun/append/(?P<trid>\d+)/?$',
        'test_secretary.views.append_testcases',
        name='append_testcases'),
    url(r'^testcaserun/edit/(?P<trid>\d+)/(?P<elemno>\d+)/?$',
        'test_secretary.views.edit_testcaserun',
        name='edit_testcaserun_multiple'),
    url(r'^testcaserun/edit/(?P<tcrid>\d+)/?$',
        'test_secretary.views.edit_testcaserun_single',
        name='edit_testcaserun_single'),
    url(r'^testcaserun/setstatus/(?P<tcrid>\d+)/(?P<status>[A-Z]{2,3})/?$',
        'test_secretary.views.set_testcaserun_status',
        name='set_testcaserun_status'),
    url(r'^app/(?P<aid>\d+)/(?P<all>all)?/?$',
        'test_secretary.views.app_overview',
        name='app_overview'),

    url(r'^unittester/', include(unittester.urls, namespace='unittester',
        app_name='unittester')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        name='generic_login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
        name='generic_logout'),
)

unittester/urls.py
from django.conf.urls import patterns, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^testcaserun/run/(?P<tcrid>\d+)/?$',
        'unittester.views.run_testcaserun', name='testcaserun'),
)

test_secretary/models.py
from dateutil import tz
from datetime import datetime

from django.db import models
from django.core import urlresolvers
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django_extensions.db.fields import ModificationDateTimeField
from django.utils.translation import ugettext as _


STATUS = (('NT', 'untested'),
          ('OK', 'success'),
          ('NOK', 'failed'),
          ('DN', 'decision needed'))


class AdminUrlMixIn():
    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        name = 'admin:%s_%s_change' % (content_type.app_label,
                                       content_type.model)
        return urlresolvers.reverse(name, args=(self.pk,))


class Application(models.Model, AdminUrlMixIn):
    name = models.CharField(max_length=50)
    order = models.PositiveIntegerField(blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('order', 'name')

    @property
    def active_sections(self):
        return self.testsection_set.filter(active=True)


class TestSection(models.Model, AdminUrlMixIn):
    name = models.CharField(max_length=50)
    app = models.ForeignKey(Application)
    active = models.BooleanField(default=True)
    order = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return '%s - %s' % (self.app, self.name)

    @property
    def active_testcases(self):
        return self.testcase_set.filter(active=True)

    class Meta:
        unique_together = ('name', 'app')
        ordering = ('app', 'order', 'name')


class TestCase(models.Model, AdminUrlMixIn):
    order = models.PositiveIntegerField(null=True, blank=True)
    name = models.CharField(max_length=100)
    section = models.ForeignKey(TestSection)
    active = models.BooleanField(default=True)
    autotest_exists = models.BooleanField(default=False)
    description = models.TextField(null=True, blank=True)
    preconditions = models.ManyToManyField('self', through='Precondition',
                                           null=True, blank=True,
                                           symmetrical=False,
                                           related_name='precondition_set')
    action = models.TextField(null=True, blank=True)
    expected = models.TextField(null=True, blank=True)

    def __str__(self):
        return '%s - %s' % (self.section, self.name)

    class Meta:
        get_latest_by = 'pk'
        ordering = ('section', 'order', 'name')


class Precondition(models.Model, AdminUrlMixIn):
    testcase = models.ForeignKey(TestCase, related_name='from_testcase')
    precondition = models.ForeignKey(TestCase, related_name='precondition')
    comment = models.TextField(null=True, blank=True)


class TestRun(models.Model, AdminUrlMixIn):
    name = models.CharField(max_length=50)
    comment = models.TextField(null=True, blank=True)
    version = models.CharField(max_length=40)
    date = models.DateTimeField(default=datetime.now, blank=True)
    testcases = models.ManyToManyField(TestCase, through='TestCaseRun')
    user = models.ForeignKey(User)

    def has_testcase_assigned(self, testcase):
        return TestCaseRun.objects.filter(
            testrun=self, testcase=testcase
        ).exists()

    def __str__(self):
        t = self.date.astimezone(tz.tzlocal())
        timestring = t.strftime('%Y-%m-%d %H:%M')
        return '[%s] %s' % (timestring, self.name)

    @property
    def assigned_applications(self):
        testcase_ids = self.testcaserun_set.values('testcase_id')
        return Application.objects.filter(
            testsection__testcase__id__in=testcase_ids).distinct()

    class Meta:
        get_latest_by = 'date'
        ordering = ['-date']
        permissions = (
            ("view_testruns", _("Can see own tests running")),
            ("view_other_testruns", _("Can see all tests running")),
        )

    @property
    def is_finished(self):
        """ no untested or undecided testcases
        """
        return self.todo_count + self.decision_count == 0

    @property
    def is_success(self):
        """ nothing failed, also check is_finished
            unfinished testruns can also be successfully if nothing failed yet
        """
        return self.failed_count == 0

    @property
    def success_count(self):
        return self.testcaserun_set.filter(status='OK').count()

    @property
    def failed_count(self):
        return self.testcaserun_set.filter(status='NOK').count()

    @property
    def todo_count(self):
        return self.testcaserun_set.filter(status='NT').count()

    @property
    def decision_count(self):
        return self.testcaserun_set.filter(status='DN').count()


class TestCaseRun(models.Model, AdminUrlMixIn):
    testcase = models.ForeignKey(TestCase)
    testrun = models.ForeignKey(TestRun)
    status = models.CharField(max_length=3, choices=STATUS, default='NT')
    comment = models.TextField(null=True, blank=True)
    modified = ModificationDateTimeField(help_text=_('Last Status Change'))
    editor = models.ForeignKey(User, help_text=_('Last Editor'))

    def __str__(self):
        return '%s: %s' % (self.testrun, self.testcase)

    class Meta:
        ordering = ('testcase__section__app__name', 'testcase__section__order',
                    'testcase__section__name', 'testcase__order')
        permissions = (
            ("view_testcaserun_status", _("Can see own tests running")),
        )

templates/base.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Test Secretary{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'css/bootstrap-switch.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'css/test_secretary.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'css/screen.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/print.css' %}" rel="stylesheet" media="print">
    {% block styles %}{% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% include "navbar.html" %}

    <div class="content-block">
      {% block logo %}
        <a href="{% url 'overview' %}">
          <img id="logo" src={% static 'img/logo.png' %}></img>
        </a>
      {% endblock %}
      {% block main %}
        <h1>Error!</h1>
        <p>Main content missing</p>
      {% endblock %}
    </div>

    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-switch.min.js' %}"></script>
    <script src="{% static 'js/testsecretary.js' %}"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/navbar.html
<div class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Test Secretary</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if perms.test_secretary.add_testrun %}
          <li><a href="{% url 'new_testrun' %}">New TestRun</a></li>
        {% endif %}
        {% if perms.test_secretary.add_testcase %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">TestCases <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li class="dropdown-header">Admin</li>
              <li><a target="_blank" href="/admin/test_secretary/testcase/">View</a></li>
              <li><a target="_blank" href="/admin/test_secretary/testcase/add/">Add New</a></li>
              <!--<li class="divider"></li>
              <li class="dropdown-header">Nav header</li>
              <li><a href="#">Separated link</a></li>
              <li><a href="#">One more separated link</a></li>-->
            </ul>
          </li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a target="_blank" href="/admin">Admin</a></li>
        {% if request.user.is_authenticated %}
          <li><a href="/accounts/logout?next=/">Logout ({{ user.username }})</a></li>
        {% else %}
          <li><a href="/accounts/login?next=/">Login</a></li>
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</div>